name: Run code generation

on:
  push:
    branches: [codegen]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn --frozen-lockfile --non-interactive
      - run: yarn generate-clients

      - run: git diff
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          branch: update-models
          title: 'feat(clients): update models as of ${{ steps.date.outputs.date }}'
          commit-message: 'feat(clients): update models as of ${{ steps.date.outputs.date }}'
