name: Run code generation

on:
  push:
    branches: [codegen]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn --frozen-lockfile --non-interactive
      - run: yarn generate-clients
      - run: git diff
